# 下面是些`numpy`的使用Demo，以获得一些体感

In [1]:
import numpy as np
import math
import scipy as sp
import scipy.special as sc

In [2]:
sc.factorial([3, 4], exact=True)

array([ 6, 24])

In [3]:
sc.factorial([3, 4])

array([ 6., 24.])

In [4]:
sc.factorial([3, 3.5, 4], exact=True)

array([   6,   84, 1512])

In [5]:
sc.factorial([3, 3.5, 4])

array([ 6.       , 11.6317284, 24.       ])

In [6]:
np.exp([1, 2, 3])

array([ 2.71828183,  7.3890561 , 20.08553692])

In [7]:
np.sin([0, math.pi/2, math.pi])

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])